"""initial schema

Revision ID: 5adcde8aa247
Revises:
Create Date: 2026-08-01 00:04:07.312233
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5adcde8aa247"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PROVISIONING",
                "ACTIVE",
                "SUSPENDED",
                name="tenant_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = lower(code)", name="ck_tenants_code_lowercase"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "catalog_imports",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "DELTA",
                "FULL",
                name="catalog_import_mode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "VALIDATING",
                "READY",
                "PROCESSING",
                "COMPLETED",
                "REJECTED",
                "FAILED",
                name="catalog_import_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("valid_rows", sa.Integer(), nullable=False),
        sa.Column("invalid_rows", sa.Integer(), nullable=False),
        sa.Column("inserted_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("unchanged_count", sa.Integer(), nullable=False),
        sa.Column("deactivated_count", sa.Integer(), nullable=False),
        sa.Column("reconciliation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes >= 0", name="ck_catalog_imports_nonnegative_size"),
        sa.CheckConstraint("total_rows >= 0", name="ck_catalog_imports_nonnegative_rows"),
        sa.CheckConstraint(
            "valid_rows + invalid_rows = total_rows", name="ck_catalog_imports_row_reconciliation"
        ),
        sa.CheckConstraint(
            "valid_rows >= 0 AND invalid_rows >= 0 "
            "AND inserted_count >= 0 AND updated_count >= 0 "
            "AND unchanged_count >= 0 AND deactivated_count >= 0",
            name="ck_catalog_imports_nonnegative_counts",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_catalog_imports_tenant_idempotency"
        ),
    )
    op.create_index(
        "ix_catalog_imports_tenant_created",
        "catalog_imports",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "devices",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("serial_number", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("credential_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                name="device_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number", name="uq_devices_serial_number"),
    )
    op.create_index("ix_devices_tenant_status", "devices", ["tenant_id", "status"], unique=False)
    op.create_table(
        "durable_jobs",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "CATALOG_IMPORT",
                "RFID_OBSERVATION",
                "REPLENISHMENT_RECALC",
                name="job_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "QUARANTINED",
                name="job_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'PROCESSING' AND locked_by IS NOT NULL "
            "AND lease_expires_at IS NOT NULL) OR status <> 'PROCESSING'",
            name="ck_durable_jobs_processing_lease",
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_durable_jobs_nonnegative_attempts"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_durable_jobs_claim",
        "durable_jobs",
        ["status", "available_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_durable_jobs_tenant_kind", "durable_jobs", ["tenant_id", "kind"], unique=False
    )
    op.create_table(
        "onboarding_batches",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "VALIDATING",
                "COMPLETED",
                "FAILED",
                name="batch_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("succeeded_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "succeeded_count + failed_count <= total_count",
            name="ck_onboarding_batches_results_within_total",
        ),
        sa.CheckConstraint(
            "succeeded_count >= 0 AND failed_count >= 0",
            name="ck_onboarding_batches_nonnegative_results",
        ),
        sa.CheckConstraint("total_count > 0", name="ck_onboarding_batches_positive_total"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_onboarding_batches_tenant_idempotency"
        ),
    )
    op.create_table(
        "organization_units",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unit_type", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = lower(code)", name="ck_org_units_code_lowercase"),
        sa.ForeignKeyConstraint(["parent_id"], ["organization_units.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_org_units_tenant_code"),
    )
    op.create_index(
        "ix_org_units_tenant_parent", "organization_units", ["tenant_id", "parent_id"], unique=False
    )
    op.create_table(
        "product_styles",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = upper(code)", name="ck_product_styles_code_uppercase"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_product_styles_tenant_code"),
    )
    op.create_index(
        "ix_product_styles_tenant_active", "product_styles", ["tenant_id", "active"], unique=False
    )
    op.create_table(
        "replenishment_policy_imports",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "COMPLETED",
                "REJECTED",
                name="policy_import_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("created_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("unchanged_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("reconciliation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("created_count >= 0", name="ck_policy_imports_nonnegative_created"),
        sa.CheckConstraint("rejected_count >= 0", name="ck_policy_imports_nonnegative_rejected"),
        sa.CheckConstraint("total_count >= 0", name="ck_policy_imports_nonnegative_total"),
        sa.CheckConstraint("unchanged_count >= 0", name="ck_policy_imports_nonnegative_unchanged"),
        sa.CheckConstraint("updated_count >= 0", name="ck_policy_imports_nonnegative_updated"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "idempotency_key",
            name="uq_replenishment_policy_imports_tenant_idempotency",
        ),
    )
    op.create_index(
        "ix_replenishment_policy_imports_tenant_created",
        "replenishment_policy_imports",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "SUSPENDED", name="user_status", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name="ck_users_email_lowercase"),
        sa.CheckConstraint("token_version >= 1", name="ck_users_token_version_positive"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
    )
    op.create_index("ix_users_tenant_status", "users", ["tenant_id", "status"], unique=False)
    op.create_table(
        "catalog_import_errors",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=True),
        sa.Column("field", sa.String(length=128), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("rejected_value", sa.String(length=500), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["import_id"], ["catalog_imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_catalog_import_errors_tenant_import",
        "catalog_import_errors",
        ["tenant_id", "import_id"],
        unique=False,
    )
    op.create_table(
        "catalog_import_rows",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("import_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("normalized_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "VALID",
                "INVALID",
                name="catalog_row_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "INSERT",
                "UPDATE",
                "UNCHANGED",
                name="catalog_row_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("row_number >= 2", name="ck_catalog_import_rows_data_row_number"),
        sa.ForeignKeyConstraint(["import_id"], ["catalog_imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_id", "row_number", name="uq_catalog_import_rows_number"),
    )
    op.create_index(
        "ix_catalog_import_rows_tenant_import",
        "catalog_import_rows",
        ["tenant_id", "import_id"],
        unique=False,
    )
    op.create_table(
        "identity_audit_records",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "LOGIN_SUCCEEDED",
                "LOGIN_FAILED",
                "USER_CREATED",
                "USER_SUSPENDED",
                name="identity_audit_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_identity_audit_actor",
        "identity_audit_records",
        ["tenant_id", "actor_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_identity_audit_tenant_occurred",
        "identity_audit_records",
        ["tenant_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "skus",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("product_style_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("upc", sa.String(length=14), nullable=False),
        sa.Column("color", sa.String(length=128), nullable=False),
        sa.Column("size", sa.String(length=64), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = upper(code)", name="ck_skus_code_uppercase"),
        sa.ForeignKeyConstraint(["product_style_id"], ["product_styles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_skus_tenant_code"),
        sa.UniqueConstraint("tenant_id", "upc", name="uq_skus_tenant_upc"),
    )
    op.create_index(
        "ix_skus_tenant_style_active",
        "skus",
        ["tenant_id", "product_style_id", "active"],
        unique=False,
    )
    op.create_table(
        "stores",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("organization_unit_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PROVISIONING",
                "ACTIVE",
                "INACTIVE",
                name="store_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = lower(code)", name="ck_stores_code_lowercase"),
        sa.ForeignKeyConstraint(
            ["organization_unit_id"], ["organization_units.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_stores_tenant_code"),
    )
    op.create_index("ix_stores_tenant_status", "stores", ["tenant_id", "status"], unique=False)
    op.create_table(
        "epc_bindings",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("epc", sa.String(length=128), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_import_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name="ck_epc_bindings_valid_interval",
        ),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_import_id"], ["catalog_imports.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_epc_bindings_resolve",
        "epc_bindings",
        ["tenant_id", "epc", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_index(
        "ix_epc_bindings_sku_active",
        "epc_bindings",
        ["tenant_id", "sku_id", "effective_to"],
        unique=False,
    )
    op.create_index(
        "uq_epc_bindings_active_tenant_epc",
        "epc_bindings",
        ["tenant_id", "epc"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.create_table(
        "replenishment_policies",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("external_key", sa.String(length=128), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column(
            "selector_type",
            sa.Enum(
                "SKU",
                "STYLE",
                "CATEGORY",
                "SIZE",
                name="policy_selector_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("selector_value", sa.String(length=128), nullable=False),
        sa.Column("minimum_floor_quantity", sa.Integer(), nullable=False),
        sa.Column("target_floor_quantity", sa.Integer(), nullable=False),
        sa.Column("maximum_floor_quantity", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name="ck_replenishment_policies_valid_interval",
        ),
        sa.CheckConstraint(
            "maximum_floor_quantity IS NULL OR maximum_floor_quantity >= target_floor_quantity",
            name="ck_replenishment_policies_maximum_at_least_target",
        ),
        sa.CheckConstraint(
            "minimum_floor_quantity >= 0", name="ck_replenishment_policies_nonnegative_minimum"
        ),
        sa.CheckConstraint(
            "target_floor_quantity >= minimum_floor_quantity",
            name="ck_replenishment_policies_target_at_least_minimum",
        ),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "external_key", name="uq_replenishment_policies_tenant_external_key"
        ),
    )
    op.create_index(
        "ix_replenishment_policies_resolution",
        "replenishment_policies",
        ["tenant_id", "store_id", "active", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_index(
        "ix_replenishment_policies_selector",
        "replenishment_policies",
        ["tenant_id", "selector_type", "selector_value"],
        unique=False,
    )
    op.create_table(
        "replenishment_runs",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum(
                "API",
                "RFID",
                "POLICY_CHANGE",
                name="replenishment_trigger",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PROCESSING",
                "COMPLETED",
                name="replenishment_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requested_by_subject", sa.String(length=255), nullable=True),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.Column("tasks_created", sa.Integer(), nullable=False),
        sa.Column("tasks_updated", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("line_count >= 0", name="ck_replenishment_runs_nonnegative_lines"),
        sa.CheckConstraint("tasks_created >= 0", name="ck_replenishment_runs_nonnegative_created"),
        sa.CheckConstraint("tasks_updated >= 0", name="ck_replenishment_runs_nonnegative_updated"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_replenishment_runs_tenant_idempotency"
        ),
    )
    op.create_index(
        "ix_replenishment_runs_tenant_store_created",
        "replenishment_runs",
        ["tenant_id", "store_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "user_access_grants",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "CORPORATE_ADMIN",
                "STORE_MANAGER",
                "STORE_ASSOCIATE",
                name="identity_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role = 'CORPORATE_ADMIN' AND store_id IS NULL) OR "
            "(role IN ('STORE_MANAGER', 'STORE_ASSOCIATE') AND store_id IS NOT NULL)",
            name="ck_user_access_grants_role_scope",
        ),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_access_grants_tenant_store",
        "user_access_grants",
        ["tenant_id", "store_id"],
        unique=False,
    )
    op.create_index(
        "uq_user_access_grants_store_role",
        "user_access_grants",
        ["user_id", "role", "store_id"],
        unique=True,
        postgresql_where=sa.text("store_id IS NOT NULL"),
    )
    op.create_index(
        "uq_user_access_grants_tenant_role",
        "user_access_grants",
        ["user_id", "role"],
        unique=True,
        postgresql_where=sa.text("store_id IS NULL"),
    )
    op.create_table(
        "zones",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "SALES_FLOOR",
                "BACKROOM",
                "RECEIVING",
                "OTHER",
                name="zone_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = lower(code)", name="ck_zones_code_lowercase"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "code", name="uq_zones_store_code"),
    )
    op.create_index(
        "ix_zones_tenant_store_kind", "zones", ["tenant_id", "store_id", "kind"], unique=False
    )
    op.create_table(
        "device_assignments",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name="ck_device_assignments_valid_interval",
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_device_assignments_lookup",
        "device_assignments",
        ["tenant_id", "device_id", "effective_from", "effective_to"],
        unique=False,
    )
    op.create_index(
        "uq_device_assignments_active_device",
        "device_assignments",
        ["tenant_id", "device_id"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.create_table(
        "inventory_balances",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name="ck_inventory_balances_nonnegative_quantity"),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "store_id", "zone_id", "sku_id", name="uq_inventory_balances_location_sku"
        ),
    )
    op.create_index(
        "ix_inventory_balances_store_sku",
        "inventory_balances",
        ["tenant_id", "store_id", "sku_id"],
        unique=False,
    )
    op.create_table(
        "inventory_item_states",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("epc", sa.String(length=128), nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("zone_id", sa.UUID(), nullable=False),
        sa.Column("candidate_store_id", sa.UUID(), nullable=True),
        sa.Column("candidate_zone_id", sa.UUID(), nullable=True),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_event_id", sa.String(length=128), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(candidate_store_id IS NULL) = (candidate_zone_id IS NULL)",
            name="ck_inventory_item_states_candidate_location",
        ),
        sa.CheckConstraint("candidate_count >= 0", name="ck_inventory_item_states_candidate_count"),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_inventory_item_states_confidence"
        ),
        sa.ForeignKeyConstraint(["candidate_store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["candidate_zone_id"], ["zones.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "epc", name="uq_inventory_item_states_tenant_epc"),
    )
    op.create_index(
        "ix_inventory_item_states_location",
        "inventory_item_states",
        ["tenant_id", "store_id", "zone_id"],
        unique=False,
    )
    op.create_table(
        "replenishment_tasks",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("source_policy_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLAIMED",
                "IN_PROGRESS",
                "AWAITING_VERIFICATION",
                "VERIFIED",
                "CANCELLED",
                "EXCEPTION",
                name="replenishment_task_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("moved_quantity", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("claimed_by_subject", sa.String(length=255), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_note", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "moved_quantity >= 0 AND moved_quantity <= quantity",
            name="ck_replenishment_tasks_valid_moved_quantity",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_replenishment_tasks_positive_quantity"),
        sa.CheckConstraint("version >= 1", name="ck_replenishment_tasks_positive_version"),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["source_policy_id"], ["replenishment_policies.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_replenishment_tasks_tenant_store_status",
        "replenishment_tasks",
        ["tenant_id", "store_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_replenishment_tasks_active_store_sku",
        "replenishment_tasks",
        ["tenant_id", "store_id", "sku_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('OPEN', 'CLAIMED', 'IN_PROGRESS', 'AWAITING_VERIFICATION')"
        ),
    )
    op.create_table(
        "rfid_observations",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("batch_id", sa.String(length=128), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column("zone_id", sa.UUID(), nullable=True),
        sa.Column("epc", sa.String(length=128), nullable=False),
        sa.Column("resolved_epc_binding_id", sa.UUID(), nullable=True),
        sa.Column("resolution_strategy", sa.String(length=32), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reader_sequence", sa.Integer(), nullable=True),
        sa.Column("antenna_port", sa.Integer(), nullable=True),
        sa.Column("rssi_dbm", sa.Float(), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "PROCESSED",
                "LATE_IGNORED",
                "QUARANTINED",
                name="observation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("quarantine_reason", sa.String(length=128), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["resolved_epc_binding_id"], ["epc_bindings.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "event_id", name="uq_rfid_observations_tenant_event"),
    )
    op.create_index(
        "ix_rfid_observations_epc_time",
        "rfid_observations",
        ["tenant_id", "epc", "observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_rfid_observations_status_time",
        "rfid_observations",
        ["status", "ingested_at"],
        unique=False,
    )
    op.create_table(
        "inventory_changes",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("epc", sa.String(length=128), nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("from_store_id", sa.UUID(), nullable=True),
        sa.Column("from_zone_id", sa.UUID(), nullable=True),
        sa.Column("to_store_id", sa.UUID(), nullable=False),
        sa.Column("to_zone_id", sa.UUID(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["from_store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["from_zone_id"], ["zones.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["observation_id"], ["rfid_observations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["to_zone_id"], ["zones.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("observation_id", name="uq_inventory_changes_observation"),
    )
    op.create_index(
        "ix_inventory_changes_store_time",
        "inventory_changes",
        ["tenant_id", "to_store_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "replenishment_run_lines",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column(
            "selector_type",
            sa.Enum(
                "SKU",
                "STYLE",
                "CATEGORY",
                "SIZE",
                name="run_line_policy_selector_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("selector_value", sa.String(length=128), nullable=True),
        sa.Column("policy_priority", sa.Integer(), nullable=True),
        sa.Column("minimum_floor_quantity", sa.Integer(), nullable=True),
        sa.Column("target_floor_quantity", sa.Integer(), nullable=True),
        sa.Column("maximum_floor_quantity", sa.Integer(), nullable=True),
        sa.Column("floor_quantity", sa.Integer(), nullable=False),
        sa.Column("backroom_quantity", sa.Integer(), nullable=False),
        sa.Column("open_task_quantity", sa.Integer(), nullable=False),
        sa.Column("recommended_quantity", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "NO_MATCHING_POLICY",
                "FLOOR_AT_OR_ABOVE_MINIMUM",
                "OPEN_TASK_COVERS_NEED",
                "NO_BACKROOM_STOCK",
                "REPLENISHMENT_REQUIRED",
                name="replenishment_reason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("formula", sa.String(length=500), nullable=False),
        sa.Column("inventory_as_of", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "floor_quantity >= 0 AND backroom_quantity >= 0 "
            "AND open_task_quantity >= 0 AND recommended_quantity >= 0",
            name="ck_replenishment_run_lines_nonnegative_quantities",
        ),
        sa.ForeignKeyConstraint(["policy_id"], ["replenishment_policies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["replenishment_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["replenishment_tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "sku_id", name="uq_replenishment_run_lines_run_sku"),
    )
    op.create_index(
        "ix_replenishment_run_lines_tenant_store_sku",
        "replenishment_run_lines",
        ["tenant_id", "store_id", "sku_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_replenishment_run_lines_tenant_store_sku", table_name="replenishment_run_lines"
    )
    op.drop_table("replenishment_run_lines")
    op.drop_index("ix_inventory_changes_store_time", table_name="inventory_changes")
    op.drop_table("inventory_changes")
    op.drop_index("ix_rfid_observations_status_time", table_name="rfid_observations")
    op.drop_index("ix_rfid_observations_epc_time", table_name="rfid_observations")
    op.drop_table("rfid_observations")
    op.drop_index(
        "uq_replenishment_tasks_active_store_sku",
        table_name="replenishment_tasks",
        postgresql_where=sa.text(
            "status IN ('OPEN', 'CLAIMED', 'IN_PROGRESS', 'AWAITING_VERIFICATION')"
        ),
    )
    op.drop_index("ix_replenishment_tasks_tenant_store_status", table_name="replenishment_tasks")
    op.drop_table("replenishment_tasks")
    op.drop_index("ix_inventory_item_states_location", table_name="inventory_item_states")
    op.drop_table("inventory_item_states")
    op.drop_index("ix_inventory_balances_store_sku", table_name="inventory_balances")
    op.drop_table("inventory_balances")
    op.drop_index(
        "uq_device_assignments_active_device",
        table_name="device_assignments",
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.drop_index("ix_device_assignments_lookup", table_name="device_assignments")
    op.drop_table("device_assignments")
    op.drop_index("ix_zones_tenant_store_kind", table_name="zones")
    op.drop_table("zones")
    op.drop_index(
        "uq_user_access_grants_tenant_role",
        table_name="user_access_grants",
        postgresql_where=sa.text("store_id IS NULL"),
    )
    op.drop_index(
        "uq_user_access_grants_store_role",
        table_name="user_access_grants",
        postgresql_where=sa.text("store_id IS NOT NULL"),
    )
    op.drop_index("ix_user_access_grants_tenant_store", table_name="user_access_grants")
    op.drop_table("user_access_grants")
    op.drop_index("ix_replenishment_runs_tenant_store_created", table_name="replenishment_runs")
    op.drop_table("replenishment_runs")
    op.drop_index("ix_replenishment_policies_selector", table_name="replenishment_policies")
    op.drop_index("ix_replenishment_policies_resolution", table_name="replenishment_policies")
    op.drop_table("replenishment_policies")
    op.drop_index(
        "uq_epc_bindings_active_tenant_epc",
        table_name="epc_bindings",
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.drop_index("ix_epc_bindings_sku_active", table_name="epc_bindings")
    op.drop_index("ix_epc_bindings_resolve", table_name="epc_bindings")
    op.drop_table("epc_bindings")
    op.drop_index("ix_stores_tenant_status", table_name="stores")
    op.drop_table("stores")
    op.drop_index("ix_skus_tenant_style_active", table_name="skus")
    op.drop_table("skus")
    op.drop_index("ix_identity_audit_tenant_occurred", table_name="identity_audit_records")
    op.drop_index("ix_identity_audit_actor", table_name="identity_audit_records")
    op.drop_table("identity_audit_records")
    op.drop_index("ix_catalog_import_rows_tenant_import", table_name="catalog_import_rows")
    op.drop_table("catalog_import_rows")
    op.drop_index("ix_catalog_import_errors_tenant_import", table_name="catalog_import_errors")
    op.drop_table("catalog_import_errors")
    op.drop_index("ix_users_tenant_status", table_name="users")
    op.drop_table("users")
    op.drop_index(
        "ix_replenishment_policy_imports_tenant_created", table_name="replenishment_policy_imports"
    )
    op.drop_table("replenishment_policy_imports")
    op.drop_index("ix_product_styles_tenant_active", table_name="product_styles")
    op.drop_table("product_styles")
    op.drop_index("ix_org_units_tenant_parent", table_name="organization_units")
    op.drop_table("organization_units")
    op.drop_table("onboarding_batches")
    op.drop_index("ix_durable_jobs_tenant_kind", table_name="durable_jobs")
    op.drop_index("ix_durable_jobs_claim", table_name="durable_jobs")
    op.drop_table("durable_jobs")
    op.drop_index("ix_devices_tenant_status", table_name="devices")
    op.drop_table("devices")
    op.drop_index("ix_catalog_imports_tenant_created", table_name="catalog_imports")
    op.drop_table("catalog_imports")
    op.drop_table("tenants")
    # ### end Alembic commands ###
